"""Add alert thresholds to Material

Revision ID: 55f216f14aa0
Revises: baaccadf2279
Create Date: 2025-11-03 10:26:06.976936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f216f14aa0'
down_revision = 'baaccadf2279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yellow_alert', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_alert', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('red_alert')
        batch_op.drop_column('yellow_alert')

    # ### end Alembic commands ###
