"""Add rate column to FinishedProduct

Revision ID: baaccadf2279
Revises: 
Create Date: 2025-10-26 11:43:57.559613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaccadf2279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Float(precision=50), nullable=True))
        batch_op.alter_column('capacity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(precision=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_product', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.Float(precision=50),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
